spring.application.name=06-spring-boot-actuator

#management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=beans


# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Enable heapdump explicitly
management.endpoint.heapdump.enabled=true

# Shutdown Property
management.endpoint.shutdown.enabled=true