spring.application.name=10-spring-boot-redis-server

#spring.data.redis.url=rediss://default:kL5xkjGZ9PWvvVTZKGkJaUsUEbQhb1Da@redis-14281.crce179.ap-south-1-1.ec2.cloud.redislabs.com:14281

spring.data.redis.host=redis-14281.crce179.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=14281
spring.data.redis.username=default
spring.data.redis.password=kL5xkjGZ9PWvvVTZKGkJaUsUEbQhb1Da
spring.data.redis.ssl.enabled=true